version: "3.7"

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    scrapper:
        build: 
            context: ./scraper
            target: ${TARGET}
            dockerfile: docker/${OFFER_RIDER_ARCHITECTURE}/Dockerfile
        ports:
            - "3000:3000"
        links:
            - redis
        volumes:
            - ./scraper:/scrapper
        command: npm start
    frontend:
        build: 
            context: ./frontend
            target: ${TARGET}
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/frontend
        command: /bin/sh -c "yarn serve"
    search-service:
        build: ./search-service
        ports:
            - 30001:30001
    search-db:
        build: 
            context: ./search-service/db
            dockerfile: ${OFFER_RIDER_ARCHITECTURE}/Dockerfile
        environment: 
            - CREATE_DB=1
        ports: 
            - 30000:3306
