version: "3.7"

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    rebrow:
        image: marian/rebrow
        ports:
            - "5001:5001"
        links:
            - redis
    scrapper:
        build: ./scraper
        expose:
            - "3000"
        ports:
            - "3000:3000"
        links:
            - redis
        volumes:
            - ./scraper:/scrapper
        command: npm start
    frontend:
        build: ./frontend
        expose:
            - "8080"
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/frontend
        command: npm run serve

